#!/usr/bin/env python3
# Mandatory imports
import argparse
import os

# Checking for 'pandas' package
try:
    import pandas
except ImportError:
    raise ImportError("Missing package: `PANDAS`!")


def reverse_translate(amino, codon_table):
    """
    Reverse-translates aminoacid back to the most used codon from codon table.
    """
    temp_values = []
    temp_triplets = []

    for i, row in codon_table.loc[codon_table[0] == amino].iterrows():
        temp_triplets.append((row[1]).strip().upper())
        temp_values.append(row[2])
    
    return temp_triplets[temp_values.index(max(temp_values))]


def make_dna_triplets(string):
    """
    Makes chunks of 3 characters from a long string.
    """
    return [string[start:start+3] for start in range(0, len(string), 3)]


def codon_optimize(name, orf, codon_table, forced):
    """
    Checks if a given sequence starts with the start codon ('ATG') and promts you if it doesn't.
    Optimizes codons to most frequently used from codon table.
    """

    if orf[:3] != "ATG":
        if not forced:
            cont_prompt = input("Sequence with id `{0}` is not ORF, do you want to continue anyway? (Y/n): ".format(name))
        
            if cont_prompt.upper() == "Y" or cont_prompt.upper() == "YES" or cont_prompt == "":
                forced = True
            else:
                forced = False
                return False, forced
    else:
        forced = False

    optimized_orf = ""

    for triplet in make_dna_triplets(orf):
        
        if len(triplet) == 3:
            optimized_orf += reverse_translate(codon_table.loc[
                codon_table[1] == triplet][0].iloc[0][0], codon_table)
        else:
            optimized_orf += triplet

    return optimized_orf, forced


def writer(dictionary, path=None):
    """
    Simple function for writing `.fasta` files.
    """
    string = ""

    for k, v in dictionary.items():
            if v[0]:
                k += "|OPTIMIZED"
                if v[1]:
                    k += "|forced"
                string += "{0}\n{1}\n\n".format(k, v[0])

    if path:
        with open(path, 'w') as file_out:
            file_out.write(string)
    else:
        return string


def open_fasta(file_input_path):
    """
    Function for opening `.fasta` files that can contain more than just one sequence.
    Returns dictionary of sequences ==> {id: sequence}
    """
    sequence_dictionary = {}

    with open(file_input_path, 'r') as input_file:
        data = input_file.readlines()
    
    for line in data:
        temp = line.strip()
        if line[0] == ">":
            sequence_id = temp[:20]
            sequence_dictionary[sequence_id] = ""
        else:
            sequence_dictionary[sequence_id] += temp.upper()

    return sequence_dictionary


def protein_to_dna(sequences, codon_table):
    reverse_translations = {}

    for id, sequence in sequences.items():
        reverse_translations[id] = ["", None]

        for amino in sequence:
            reverse_translations[id][0] += reverse_translate(amino, codon_table)
    
    return reverse_translations


def optimize_dna(sequences, codon_table, forced):
    optimized_orfs = {}

    for id, sequence in sequences.items():
        optimized_orfs[id] = codon_optimize(id, sequence, codon_table, forced)
    
    return optimized_orfs


def main():
    """
    Main function with argument parsing.
    """
    description = ("Welcome to python script for converting protein sequence to DNA sequence with\
                    custom table for codon usage.")

    # Arguments
    parser = argparse.ArgumentParser(description=description)
    parser.add_argument("-i","--input", help="Path to input 'fasta' file", required=True)
    parser.add_argument("-t","--table",help="Path to codon usage table in csv format: 'aminoacid,triplet,value')", required=True)
    parser.add_argument("-p","--protein", action="store_true", help="Use this flag when working with protein sequences", required=False)
    parser.add_argument("-o", "--output", help="Name for the output fasta file", required=False)
    parser.add_argument("-f","--force", action="store_true", help="Use this flag to omit any prompts", required=False)
    args = parser.parse_args()

    # Variables
    current_dir = os.path.dirname(os.path.realpath(__file__))
    path_fasta = "{0}/{1}".format(current_dir, args.input)
    path_table = "{0}/{1}".format(current_dir, args.table)
    codon_table = pandas.read_csv(path_table, header=None)
    sequences = open_fasta(path_fasta)

    # Protein translation
    if args.protein:
        solution = protein_to_dna(sequences, codon_table)

    elif not args.protein:
        solution = optimize_dna(sequences, codon_table, args.force)

    # Saving/Printing solution(s)
    if args.output:
        path_save = "{0}/{1}".format(current_dir, args.output)
        msg_saved = "Output saved to `{0}`".format(args.output)
        writer(solution, path_save)
        print(msg_saved)
    else:
        print(writer(solution))


if __name__ == "__main__":
    main()